"""Phase 3.5 — zero-touch environment apply (headless build→world).

Runs a generated HermesForge project's `environment_apply.gd` headless so the
environment: block (terrain / water / foliage / sky) is realized in-scene and
saved to main.tscn — no editor session required.

Prereqs: a Godot binary (arg, $GODOT_BIN, or PATH) and a project generated by
the GodotAdapter v2 (it ships environment_apply.gd + the hermes_bridge addon).
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

# How long to let the headless apply run before giving up (terrain gen at 1024m
# is the slow step; ~30s typical, generous ceiling for larger worlds).
DEFAULT_TIMEOUT = 180


def find_godot(explicit: str = "") -> str | None:
    """Locate a Godot binary: explicit path, $GODOT_BIN, then PATH."""
    if explicit:
        return explicit if Path(explicit).exists() else None
    env = os.environ.get("GODOT_BIN")
    if env and Path(env).exists():
        return env
    for name in ("godot", "godot4", "godot-headless"):
        found = shutil.which(name)
        if found:
            return found
    return None


def apply_environment(
    project_dir: str,
    godot: str = "",
    timeout: int = DEFAULT_TIMEOUT,
) -> dict:
    """Run environment_apply.gd headless in a generated project.

    Returns a dict: {success, returncode, applied, log, project_dir}. `applied`
    lists the [env_apply] PASS lines from the Godot log for a compact report.
    """
    project = Path(project_dir)
    script = project / "environment_apply.gd"
    result: dict = {
        "success": False, "returncode": -1, "applied": [],
        "log": "", "project_dir": str(project),
    }

    if not project.exists():
        result["log"] = f"project dir not found: {project}"
        return result
    if not script.exists():
        result["log"] = (
            "environment_apply.gd not found — this project was not generated "
            "with the HermesForge environment stack (schema v2 environment: block)."
        )
        return result

    godot_bin = find_godot(godot)
    if not godot_bin:
        result["log"] = "Godot binary not found (set GODOT_BIN or install godot on PATH)"
        return result

    cmd = [godot_bin, "--headless", "--path", str(project), "--script", "res://environment_apply.gd"]
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout, cwd=str(project),
        )
    except subprocess.TimeoutExpired:
        result["log"] = f"apply timed out after {timeout}s"
        return result

    out = (proc.stdout or "") + (proc.stderr or "")
    result["returncode"] = proc.returncode
    result["log"] = out
    result["applied"] = [
        line.split("PASS: ", 1)[1].strip()
        for line in out.splitlines()
        if "[env_apply] PASS:" in line
    ]
    result["success"] = proc.returncode == 0
    return result
