export function generateProjectGodot(data: Record<string, unknown>): string {
  const meta = (data.meta || {}) as Record<string, unknown>;
  const env = (data.environment_config || {}) as Record<string, unknown>;
  const physics = (env.physics || {}) as Record<string, unknown>;

  const title = String(meta.title || "ForgeDNA Game");
  const gravityVec = (physics.gravity_vector || [0, -9.8, 0]) as number[];
  const gravityMagnitude = Math.abs(gravityVec[1] ?? 9.8);
  const gravityDirX = gravityVec[0] ?? 0;
  const gravityDirY = gravityVec[1] !== undefined ? (gravityVec[1] < 0 ? -1 : 1) : -1;
  const gravityDirZ = gravityVec[2] ?? 0;
  const defaultFriction = Number(physics.default_friction ?? 0.5);
  const terminalVelocity = Number(physics.terminal_velocity ?? 50);

  return `; Engine configuration file.
; Generated by ForgeDNA Deterministic Forge
; Do not edit — regenerate from your GameDNA JSON.
; GameDNA default_friction=${defaultFriction}, terminal_velocity=${terminalVelocity}

config_version=5

[application]

config/name="${title}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.3", "Forward Plus")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1152
window/size/viewport_height=648

[physics]

3d/default_gravity=${gravityMagnitude}
3d/default_gravity_vector=Vector3(${gravityDirX}, ${gravityDirY}, ${gravityDirZ})
3d/solver/contact_max_allowed_penetration=0.01
common/physics_ticks_per_second=90

[rendering]

renderer/rendering_method="forward_plus"
anti_aliasing/quality/msaa_3d=2

[autoload]

WorldConfig="*res://scripts/world_config.gd"

[xr]

openxr/enabled=true
openxr/default_action_map="res://openxr_action_map.tres"
openxr/submit_depth_buffer=true
shaders/enabled=true
`;
}
